In [1]:
import numpy as np

# 단일 객체 저장 및 불러오기
array = np.arange(0, 10)
np.save('saved.npy', array)

result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
# 복수 객체 저장 및 불러오기
array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
print(array1)
print(array2)

np.savez('saved.npz', array1=array1, array2=array2)

data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [3]:
# Numpy 원소 오름차순 정렬
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array)

# Numpy 원소 내림차순 정렬
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array[::-1])

[ 1  3  5  9 10]
[10  9  5  3  1]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [7]:
# 각 row 열을 기준으로 정렬 
array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
print(array)
print(array[0][1])
print(array[1][1])
array.sort(axis=0)
print(array[0][1])
print(array[1][1])

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
9
3
3
9


In [9]:
# 0 ~ 10, 5 elements, 균일한 간격으로 데이터 생성
array = np.linspace(0, 10, 5)
print(array)

[ 0.   2.5  5.   7.5 10. ]


In [16]:
# 난수의 재연(실행마다 결과 동일)
np.random.seed(7)
print(np.random.randint(0, 10, (2, 3)))
print(np.random.randint(0, 20, (2, 3)))
print(np.random.randint(0, 30, (2, 3)))
print(np.random.randint(0, 40, (2, 3)))

np.random.seed(7)
print(np.random.randint(0, 10, (2, 3)))
print(np.random.randint(0, 20, (2, 3)))
print(np.random.randint(0, 30, (2, 3)))
print(np.random.randint(0, 40, (2, 3)))

[[4 9 6]
 [3 3 7]]
[[ 7 14  8]
 [14 10  8]]
[[ 7  6  4]
 [16  7 12]]
[[ 0 11  6]
 [19  5 24]]
[[4 9 6]
 [3 3 7]]
[[ 7 14  8]
 [14 10  8]]
[[ 7  6  4]
 [16  7 12]]
[[ 0 11  6]
 [19  5 24]]


In [18]:
# Numpy 배열 객체 복사
array1 = np.arange(0, 10)
array2 = array1.copy()
print(array1)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [19]:
# 중복된 원소 제거
array = np.array([1, 1, 2, 3, 3, 3, 1])
print(np.unique(array))

[1 2 3]
