Python의 Numpy 라이브러리는 기본적인 상수 연산이 가능합니다.

In [1]:
import numpy as np

array = np.random.randint(1, 10, size=4).reshape(2, 2)
print(array)
result_array = array * 10
print(result_array)

[[6 3]
 [7 8]]
[[60 30]
 [70 80]]


In [2]:
array1 = np.arange(4).reshape(2, 2)
array2 = np.arange(2)
print(array1)
print(array2)
array3 = array1 + array2

print(array3)

[[0 1]
 [2 3]]
[0 1]
[[0 2]
 [2 4]]


In [3]:
array1 = np.arange(0, 8).reshape(2, 4)
array2 = np.arange(0, 8).reshape(2, 4)
print(array1)
print(array2)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]


In [4]:
array3 = np.concatenate([array1, array2], axis=0)
print(array3)
array5 = np.concatenate([array1, array2], axis=1)
print(array5)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]]


In [5]:
array4 = np.arange(0, 4).reshape(4, 1)
print(array3)
print(array4)
print(array3+array4)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


masking calculation

In [6]:
array1 = np.arange(16).reshape(2, 8)
print(array1)

array2 = array1 < 12
print(array2)

array1[array2] = 100
print(array1)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[ True  True  True  True  True  True  True  True]
 [ True  True  True  True False False False False]]
[[100 100 100 100 100 100 100 100]
 [100 100 100 100  12  13  14  15]]


In [7]:
array = np.arange(20).reshape(4, 5)

print("최대값:", np.max(array))
print("최소값:", np.min(array))
print("합계:", np.sum(array))
print("평균값:", np.mean(array))

최대값: 19
최소값: 0
합계: 190
평균값: 9.5
