In [5]:
## Numpy의 기본 사용법

import numpy as np

array = np.array([1, 2, 3])
print(array.size) # 배열의 크기
print(array.dtype) # 배열 원소의 타입
print(array[1]) # 인덱스 2의 원소

3
int32
2


In [2]:
# 0부터 10까지의 배열 만들기
array1 = np.arange(11)
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [7]:
# 0으로 초기화
array2 = np.zeros((3,5), dtype=int)
print(array2)


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [8]:
# 1로 초기화
array3 = np.ones((2, 3), dtype=str)
print(array3)

[['1' '1' '1']
 ['1' '1' '1']]


In [10]:
# 0부터 7까지 랜덤하게 초기화 된 배열 만들기
array4 = np.random.randint(0, 20, (2, 4))
print(array4)

[[16  0  0  9]
 [ 4  3  3 19]]


In [11]:
# 평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0, 1, (4, 3))
print(array5)

[[ 0.89205426  0.46884233 -0.83535054]
 [-1.43746154 -0.01650154 -0.55262402]
 [-0.48794449  0.69762217 -0.25658563]
 [-0.40033791 -1.9697756   0.81777718]]


In [13]:
array1 = np.array([1, 2, 3]) 
array2 = np.array([4, 5, 6, 8])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(7,)
[1 2 3 4 5 6 8]


In [23]:
array1 = np.arange(2).reshape(2, 1)
array2 = np.arange(8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=1)
print(array1)
print(array2)
print(array3.shape)
print(array3)

[[0]
 [1]]
[[0 1 2 3]
 [4 5 6 7]]
(2, 5)
[[0 0 1 2 3]
 [1 4 5 6 7]]


In [25]:
array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape((2, 2))
print(array2.shape)

(2, 2)
(2, 2)
(2, 2)
7


In [26]:
array = np.arange(8).reshape(2, 4)
left, right = np.split(array, [2], axis=1)
print(array)
print(left.shape)
print(right.shape)
print(right[1][1])

[[0 1 2 3]
 [4 5 6 7]]
(2, 2)
(2, 2)
7


In [45]:
array2 = np.arange(10,20,1).reshape(5,2) #start, end, step
print(array2)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [47]:
low, high = np.split(array2, [3], axis=0)
print(low.shape)
print(high.shape)
print(high[1][1])

(3, 2)
(2, 2)
19
